title = "FastGate"
version = "2.2"
loglevel = "DEBUG"
deviceid = "e4:5f:01:82:7b:03"
updated_config = 1
standalone_system = 0
tag_form = "EPC"
static_ipv4 = "192.168.1.203"

[app]
devicehbinterval = 30
transactionpost = 0
check_internet = 1
hotspot = "aviaccess"
heartbeat_time = 30
boom_on_time = 6
red_led_on_time = 2
service_activation_flag = 1

[rfid]
oem_epc = "692d54454b72666964746167"
tagType = "both"
encode_method = 1
max_encode_retry = 3
reader = "MRU102"
reader_id = ""
epc_mask = ""
interface = "serial"
baudrate = 38400
parity = "NONE"
port = "/dev/ttyS0"
reader_ip = "192.168.6.15"
reader_port = 10001
antennas = [ [ 1, 200, 0,], [ 2, 200, 0,], [ 3, 500, 0,], [ 4, 500, 0,],]
antennas_name = [ "IN", "OUT", "NA", "NA",]
ant_location = [ "Main gate", "Main Gate", "location3", "location4",]
epc_len = 24

[gpio]
boom_on_time = 4
red_led_on_time = 3
buzzer_on_time = 0.5
buzzer_off_time = 0.5
io_blink_on_time = 0.5
io_blink_off_time = 0.5
io_time_bounce = 0.5

[api]
url = ""
config = "/api/config"
configupdate = "/api/configupdate"
errorlog = "/api/errorlog"
moves = "/api/moves"
sync = "/api/sync"
token = "YXBpdXNlcjphcGl1c2Vy"

[database]
db_path = "database/itekAVI.sqlite3"
max_trans_count = 100000
max_vehicle_count = 10000

[controller]
use_local_config = 0
max_config_retry = 5
config_retry_time = 15
heartbeat_time = 30
get_config_wait_time = 15

[gpio.boom_config]
booms = [ [ 1, 3, 1, 1, 1, 1, 4,], [ 1, 3, 1, 1, 1, 1, 4,], [ 0, 6, 1, 1, 1, 1, 4,], [ 0, 6, 1, 1, 1, 1, 4,],]

[gpio.in_pin]
safety_boom = [ 12, 36, 38, 40,]

[gpio.out_pin]
boom_output = [ 7, 29, 7, 7,]
green_led = [ 31, 26,]
invaid_led = [ 24, 24, 32, 33,]
board_relays = [ 7, 21, 24, 26, 29, 31, 33,]
app_running = 13
scanning_mode = 12
error_mode = 11
buzzer = 23
prog_running = 19

[controller.config]
C01DongleResetTime = "10"
C02UhfReaderBudRate = "04"
C03TimeZone = "+0530"
C04WbEnable = "1"
C05MaxStackLevel = "04"
HeightRangeLevel1 = "0100"
HeightRangeLevel2 = "0300"
HeightRangeLevel3 = "0400"
HeightRangeLevel4 = "0500"
HeightRangeLevel5 = "0700"
HeightRangeLevel6 = "0000"
HeightRangeLevel7 = "0000"
C06LowerBoardEnable = "0"
C07TagExitTimeCount = "03"

[mqtt.connection]
broker_address = "216.69.244.100"
port = 1883
user_id = "user"
password = "Admin@123"

[mqtt.topic]
HB_pub = "HeartBeat"
pub = "SubConfigDevice"
sub = "ConfigDevice"

[mqtt.channel]
HB_pub = "HeartBeat"
startup_pub = "AVI/devicedata"
sub = [ "AVI/UserConfigDevice/<DeviceId>",]
pub = "AVI/devicedata"
vehicle_transaction = "AVI/devicedata"
